export const QueryKeys = {
  GET_AUTH_ME: "GET_AUTH_ME",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_BY_ID: "GET_CATEGORIES_BY_ID",
  GET_CONTRACT: "GET_CONTRACT",
  GET_CONTRACT_BY_ID: "GET_CONTRACT_BY_ID",
  GET_REVIEW: "GET_REVIEW",
  GET_REVIEW_BY_ID: "GET_REVIEW_BY_ID",
  GET_SERVICES: "GET_SERVICES",
  GET_SERVICES_BY_ID: "GET_SERVICES_BY_ID",
  GET_USERS: "GET_USERS",
  GET_USERS_BY_ID: "GET_USERS_BY_ID",
};
